apiVersion: apps/v1
kind: Deployment
metadata:
  name: saga-step-worker
  namespace: booking-rush
  labels:
    app: saga-step-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saga-step-worker
  template:
    metadata:
      labels:
        app: saga-step-worker
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: saga-step-worker
          image: ghcr.io/nat-prohmpiriya/booking-rush/saga-step-worker:8865cbf
          imagePullPolicy: Always
          env:
            - name: SERVICE_NAME
              value: "saga-step-worker"
          envFrom:
            - configMapRef:
                name: booking-rush-config
            - secretRef:
                name: booking-rush-secrets
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
